# Generated by Django 6.1 on 2026-08-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField(help_text='Length in cm')),
                ('width', models.FloatField(help_text='Width in cm')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internal_length', models.FloatField(help_text='Internal length in cm')),
                ('internal_width', models.FloatField(help_text='Internal width in cm')),
                ('internal_height', models.FloatField(help_text='Internal height in cm')),
                ('max_weight_capacity', models.FloatField(help_text='Max weight in kg')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost in USD', max_digits=8)),
            ],
        ),
    ]
